library(dplyr)

############### Creating list of functions for test purpose ##################
scale_function = function(x){
  return(scale(x)[,1])
}


abs_function = function(x){
  return(abs(x))
}


min_max_function = function(x,type,na.rm=TRUE){
  if(type=='min'){
    return(min(x,na.rm = na.rm))
  }
  if(type=='max'){
    return(max(x,na.rm = na.rm))
  }
  
}

################################ Dummy data ###################################

data <- c(1, 2, 3, 4, 5)
  


########################### Code string generator #############################


code_string_generator<-function(data_name,order_of_functions){
  code = paste0("as.data.frame(",data_name,")")
  
  for (i in 1:length(order_of_functions)) {
    
    name <- names(order_of_functions[i])
    args <- unlist(order_of_functions[i])
    if(is.null(args)){
      code = paste0(code," %>%\n  ",name,"()")
    }
    else{
      code_argument = ""
      for(j in 1:length(args)){
        arg_name <- gsub(paste0(name,"."), "", names(args[j]))
        arg_value <- unlist(args[j])
        code_argument = paste0(code_argument,arg_name,"='",arg_value,"',")
      }
      code_argument <- substr(code_argument, 1, nchar(code_argument) - 1)
      code = paste0(code," %>%\n  ",name,"(",code_argument,")")
    }
    
  }
  
  return(code)
}


################################ Order of functions ###########################

#This list has to be generated by the UI based on the inputs selected by the
#user

order_of_functions = list("scale_function" = list(),
                          "abs_function" = list(),
                          "min_max_function" = list(type="min",na.rm=TRUE))

#Below function will generate the code string
code<-code_string_generator("data",order_of_functions)

#The below line parses and executes the string generated
eval(parse(text=code))

cat(code)

